name: Release
on:
  push:
    branches: [master]
  workflow_dispatch: # For dev publishing

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  id-token: write # Required for OIDC / trusted publishing
  contents: write # Required for changesets pushing commits
  pull-requests: write # Required for changesets creating PRs

jobs:
  release:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: journeyapps-platform/ci-actions
          token: ${{ secrets.SHARED_GH_TOKEN }}
          path: .github/ci
          ref: v1

      - name: Enable Corepack
        run: corepack enable


      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm


      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Install dependencies
        run: pnpm install


      - name: Has changesets
        uses: bluwy/detect-changesets-action@v1
        id: detect

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          version: pnpm changeset:version
          publish: ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dev publish
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: pnpm ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}